Update 5-trigger.yml

diff --git a/.github/workflows/5-trigger.yml b/.github/workflows/5-trigger.yml
--- a/.github/workflows/5-trigger.yml
+++ b/.github/workflows/5-trigger.yml
@@ -58,9 +58,67 @@ jobs:
 
       # In README.md, switch step 5 for step X.
       - name: Update to step X
-        uses: skills/action-update-step@v2
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          from_step: 5
-          to_step: X
-          branch_name: test-workflow
+        run: |
+          echo "Check that all required env variables are set"
+          if [ -z "$TO_STEP" ]
+          then
+            echo "TO_STEP is unset or set to the empty string"
+            exit 1
+          fi
+          if [ -z "$FROM_STEP" ]
+          then
+            echo "FROM_STEP is unset or set to the empty string"
+            exit 1
+          fi
+          if [ -z "$GITHUB_TOKEN" ]
+          then
+            echo "GITHUB_TOKEN is unset or set to the empty string"
+            exit 1
+          fi
+          
+          echo "Make sure we are on the base branch ($BASE_BRANCH_NAME)"
+          git checkout $BASE_BRANCH_NAME
+          
+          echo "Pull the latest changes from remote"
+          git pull origin $BASE_BRANCH_NAME --rebase
+          
+          echo "Check that we are on FROM_STEP"
+          if [ "$(cat .github/steps/-step.txt)" != $FROM_STEP ]
+          then
+            echo "Current step is not $FROM_STEP"
+            exit 0
+          fi
+          
+          echo "Update the step to TO_STEP"
+          NEXT_STEP=$(cat .github/steps/[$TO_STEP]-*.md)
+          HEADER=$(awk '/<header>/,/<\/header>/' README.md)
+          FOOTER=$(awk '/<footer>/,/<\/footer>/' README.md)
+          echo -e "$HEADER\n\n$NEXT_STEP\n\n$FOOTER" > README.md
+          
+          echo "Update step file to TO_STEP"
+          echo "$TO_STEP" > .github/steps/-step.txt
+          
+          echo "Commit the files, and push to base branch"
+          git config user.name github-actions[bot]
+          git config user.email github-actions[bot]@users.noreply.github.com
+          git add README.md
+          git add .github/steps/-step.txt
+          git commit --message="Update to $TO_STEP in STEP and README.md"
+          git push
+          
+          echo "If BRANCH_NAME, update that branch as well"
+          if git show-ref --quiet refs/heads/$BRANCH_NAME
+          then
+            git checkout $BRANCH_NAME
+            git pull origin $BRANCH_NAME --rebase 2>/dev/null || echo "Branch is new or cannot pull, continuing..."
+            git cherry-pick $BASE_BRANCH_NAME
+            git push
+          else
+            echo "Branch $BRANCH_NAME does not exist"
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          FROM_STEP: 5
+          TO_STEP: X
+          BRANCH_NAME: test-workflow
+          BASE_BRANCH_NAME: main
